services:
  backend:
    container_name: backend_livraria
    build: 
      context: ./webacademy-livros-backend
    #volumes:
    #definir salvamento dos logs
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - livraria_network
  frontend:
    container_name: frontend_livraria
    build:
      context: ./webacademy-livros-frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
  db:
    container_name: db_loja
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql 
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - livraria_network
  phpmyadmin:
    container_name: db_loja_gui
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    networks:
      - livraria_network
    depends_on:
      - db
networks:
  livraria_network:
    driver: bridge
volumes:
  mysql_data:
  mysql_config:   

