services:
  #Back-end config.
  backend:
    container_name: backend_livraria
    build: 
      context: ./webacademy-livros-backend
    volumes:
      #- backend_logs:/app/log
      - ./webacademy-livros-backend/log:/app/log
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - livraria_network
    restart: always
    depends_on:
      db_livraria:
        condition: service_healthy

  #Front-end config.
  frontend:
    container_name: frontend_livraria
    build:
      context: ./webacademy-livros-frontend
    ports:
      - ${FRONTEND_PORT}:80
    restart: always
    depends_on:
      db_livraria:
        condition: service_healthy

  #DataBase config.
  db_livraria:
    container_name: db_livraria
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./webacademy-livros-config/configuracao:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - livraria_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 0s
      timeout: 30s
      retries: 10
      start_period: 20s
      start_interval: 1s
  #GuiDataBase config.
  phpmyadmin:
    container_name: db_livraria_gui
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db_livraria
      - PMA_PORT=3306
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    networks:
      - livraria_network
    depends_on:
      db_livraria:
        condition: service_healthy
networks:
  livraria_network:
    driver: bridge
volumes:
  mysql_data:
  #backend_logs:  
